flutter clean// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWXQO2e4sGum0kHMDLk7CjPQ9sz26v12E',
    appId: '1:80519083743:web:59db5272e06784d17b1b6a',
    messagingSenderId: '80519083743',
    projectId: 'humtooshopapp',
    authDomain: 'humtooshopapp.firebaseapp.com',
    storageBucket: 'humtooshopapp.firebasestorage.app',
    measurementId: 'G-L8Y0E4RSLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmh13X11Ctdy3n9x5sByG-PEeLdzqMF4',
    appId: '1:80519083743:android:8e1e06c077b666cc7b1b6a',
    messagingSenderId: '80519083743',
    projectId: 'humtooshopapp',
    storageBucket: 'humtooshopapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXuLSRB1WcVEdU_irfxU08KqIkFJWRq6c',
    appId: '1:80519083743:ios:327651ac16d392937b1b6a',
    messagingSenderId: '80519083743',
    projectId: 'humtooshopapp',
    storageBucket: 'humtooshopapp.firebasestorage.app',
    iosBundleId: 'com.example.laos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXuLSRB1WcVEdU_irfxU08KqIkFJWRq6c',
    appId: '1:80519083743:ios:327651ac16d392937b1b6a',
    messagingSenderId: '80519083743',
    projectId: 'humtooshopapp',
    storageBucket: 'humtooshopapp.firebasestorage.app',
    iosBundleId: 'com.example.laos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWXQO2e4sGum0kHMDLk7CjPQ9sz26v12E',
    appId: '1:80519083743:web:36c27bf78256c0917b1b6a',
    messagingSenderId: '80519083743',
    projectId: 'humtooshopapp',
    authDomain: 'humtooshopapp.firebaseapp.com',
    storageBucket: 'humtooshopapp.firebasestorage.app',
    measurementId: 'G-75YD3DN1SS',
  );
}
